<?php

namespace Database\Seeders;

use App\Models\StockOption;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class StockOptionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $options = [
            [
                'stock_item_id' => '1',
                'stock_unit_id' => '4',
                'deductable' => '50',
                'retail_price' => '76',
                'special_price' => null,
                'weight_gram' => '200',
                'length_cm' => '18',
                'height_cm' => '2',
                'width_cm' => '7',
                'is_active' => '1',
            ],
            [
                'stock_item_id' => '2',
                'stock_unit_id' => '4',
                'deductable' => '50',
                'retail_price' => '76',
                'special_price' => null,
                'weight_gram' => '200',
                'length_cm' => '18',
                'height_cm' => '2',
                'width_cm' => '7',
                'is_active' => '1',
            ],
            [
                'stock_item_id' => '6',
                'stock_unit_id' => '4',
                'deductable' => '50',
                'retail_price' => '76',
                'special_price' => null,
                'weight_gram' => '18',
                'length_cm' => '18',
                'height_cm' => '2',
                'width_cm' => '7',
                'is_active' => '1',
            ],
            [
                'stock_item_id' => '7',
                'stock_unit_id' => '4',
                'deductable' => '50',
                'retail_price' => '123.5',
                'special_price' => null,
                'weight_gram' => '200',
                'length_cm' => '18',
                'height_cm' => '2',
                'width_cm' => '7',
                'is_active' => '1',
            ],
            [
                'stock_item_id' => '9',
                'stock_unit_id' => '4',
                'deductable' => '50',
                'retail_price' => '123.5',
                'special_price' => null,
                'weight_gram' => '200',
                'length_cm' => '18',
                'height_cm' => '2',
                'width_cm' => '7',
                'is_active' => '1',
            ],
            [
                'stock_item_id' => '10',
                'stock_unit_id' => '4',
                'deductable' => '50',
                'retail_price' => '171',
                'special_price' => null,
                'weight_gram' => '200',
                'length_cm' => '18',
                'height_cm' => '2',
                'width_cm' => '7',
                'is_active' => '1',
            ],
            [
                'stock_item_id' => '11',
                'stock_unit_id' => '4',
                'deductable' => '50',
                'retail_price' => '171',
                'special_price' => null,
                'weight_gram' => '200',
                'length_cm' => '18',
                'height_cm' => '2',
                'width_cm' => '7',
                'is_active' => '1',
            ],
            [
                'stock_item_id' => '13',
                'stock_unit_id' => '4',
                'deductable' => '50',
                'retail_price' => '228',
                'special_price' => null,
                'weight_gram' => '200',
                'length_cm' => '18',
                'height_cm' => '2',
                'width_cm' => '7',
                'is_active' => '1',
            ],
            [
                'stock_item_id' => '14',
                'stock_unit_id' => '4',
                'deductable' => '50',
                'retail_price' => '76',
                'special_price' => null,
                'weight_gram' => '200',
                'length_cm' => '18',
                'height_cm' => '2',
                'width_cm' => '7',
                'is_active' => '1',
            ],
            [
                'stock_item_id' => '15',
                'stock_unit_id' => '4',
                'deductable' => '50',
                'retail_price' => '76',
                'special_price' => null,
                'weight_gram' => '200',
                'length_cm' => '18',
                'height_cm' => '2',
                'width_cm' => '7',
                'is_active' => '1',
            ],
            [
                'stock_item_id' => '16',
                'stock_unit_id' => '4',
                'deductable' => '50',
                'retail_price' => '123.5',
                'special_price' => null,
                'weight_gram' => '200',
                'length_cm' => '18',
                'height_cm' => '2',
                'width_cm' => '7',
                'is_active' => '1',
            ],
            [
                'stock_item_id' => '18',
                'stock_unit_id' => '4',
                'deductable' => '50',
                'retail_price' => '123.5',
                'special_price' => null,
                'weight_gram' => '200',
                'length_cm' => '18',
                'height_cm' => '2',
                'width_cm' => '7',
                'is_active' => '1',
            ],
            [
                'stock_item_id' => '19',
                'stock_unit_id' => '4',
                'deductable' => '50',
                'retail_price' => '171',
                'special_price' => null,
                'weight_gram' => '200',
                'length_cm' => '18',
                'height_cm' => '2',
                'width_cm' => '7',
                'is_active' => '1',
            ],
            [
                'stock_item_id' => '20',
                'stock_unit_id' => '4',
                'deductable' => '50',
                'retail_price' => '199.5',
                'special_price' => null,
                'weight_gram' => '200',
                'length_cm' => '18',
                'height_cm' => '2',
                'width_cm' => '7',
                'is_active' => '1',
            ],
            [
                'stock_item_id' => '24',
                'stock_unit_id' => '4',
                'deductable' => '50',
                'retail_price' => '76',
                'special_price' => null,
                'weight_gram' => '200',
                'length_cm' => '18',
                'height_cm' => '2',
                'width_cm' => '7',
                'is_active' => '1',
            ],
            [
                'stock_item_id' => '25',
                'stock_unit_id' => '4',
                'deductable' => '50',
                'retail_price' => '123.5',
                'special_price' => null,
                'weight_gram' => '200',
                'length_cm' => '18',
                'height_cm' => '2',
                'width_cm' => '7',
                'is_active' => '1',
            ],
            [
                'stock_item_id' => '26',
                'stock_unit_id' => '4',
                'deductable' => '50',
                'retail_price' => '123.5',
                'special_price' => null,
                'weight_gram' => '200',
                'length_cm' => '18',
                'height_cm' => '2',
                'width_cm' => '7',
                'is_active' => '1',
            ],
            [
                'stock_item_id' => '27',
                'stock_unit_id' => '4',
                'deductable' => '50',
                'retail_price' => '171',
                'special_price' => null,
                'weight_gram' => '200',
                'length_cm' => '18',
                'height_cm' => '2',
                'width_cm' => '7',
                'is_active' => '1',
            ],
            [
                'stock_item_id' => '28',
                'stock_unit_id' => '4',
                'deductable' => '50',
                'retail_price' => '171',
                'special_price' => null,
                'weight_gram' => '200',
                'length_cm' => '18',
                'height_cm' => '2',
                'width_cm' => '7',
                'is_active' => '1',
            ],
            [
                'stock_item_id' => '29',
                'stock_unit_id' => '4',
                'deductable' => '50',
                'retail_price' => '171',
                'special_price' => null,
                'weight_gram' => '200',
                'length_cm' => '18',
                'height_cm' => '2',
                'width_cm' => '7',
                'is_active' => '1',
            ],
            [
                'stock_item_id' => '31',
                'stock_unit_id' => '4',
                'deductable' => '50',
                'retail_price' => '76',
                'special_price' => null,
                'weight_gram' => '200',
                'length_cm' => '18',
                'height_cm' => '2',
                'width_cm' => '7',
                'is_active' => '1',
            ],
            [
                'stock_item_id' => '33',
                'stock_unit_id' => '4',
                'deductable' => '50',
                'retail_price' => '123.5',
                'special_price' => null,
                'weight_gram' => '200',
                'length_cm' => '18',
                'height_cm' => '2',
                'width_cm' => '7',
                'is_active' => '1',
            ],
            [
                'stock_item_id' => '35',
                'stock_unit_id' => '4',
                'deductable' => '50',
                'retail_price' => '123.5',
                'special_price' => null,
                'weight_gram' => '200',
                'length_cm' => '18',
                'height_cm' => '2',
                'width_cm' => '7',
                'is_active' => '1',
            ],
            [
                'stock_item_id' => '36',
                'stock_unit_id' => '4',
                'deductable' => '50',
                'retail_price' => '171',
                'special_price' => null,
                'weight_gram' => '200',
                'length_cm' => '18',
                'height_cm' => '2',
                'width_cm' => '7',
                'is_active' => '1',
            ],
            [
                'stock_item_id' => '37',
                'stock_unit_id' => '4',
                'deductable' => '50',
                'retail_price' => '199.5',
                'special_price' => null,
                'weight_gram' => '200',
                'length_cm' => '18',
                'height_cm' => '2',
                'width_cm' => '7',
                'is_active' => '1',
            ],
            [
                'stock_item_id' => '49',
                'stock_unit_id' => '1',
                'deductable' => '1',
                'retail_price' => '10',
                'special_price' => null,
                'weight_gram' => '1',
                'length_cm' => '1',
                'height_cm' => '1',
                'width_cm' => '1',
                'is_active' => '1',
            ],
            [
                'stock_item_id' => '50',
                'stock_unit_id' => '1',
                'deductable' => '1',
                'retail_price' => '40.5',
                'special_price' => null,
                'weight_gram' => '1',
                'length_cm' => '1',
                'height_cm' => '1',
                'width_cm' => '1',
                'is_active' => '1',
            ],
            [
                'stock_item_id' => '60',
                'stock_unit_id' => '1',
                'deductable' => '100',
                'retail_price' => '16.26',
                'special_price' => null,
                'weight_gram' => '1',
                'length_cm' => '1',
                'height_cm' => '1',
                'width_cm' => '1',
                'is_active' => '1',
            ],
            [
                'stock_item_id' => '61',
                'stock_unit_id' => '1',
                'deductable' => '100',
                'retail_price' => '22.08',
                'special_price' => null,
                'weight_gram' => '1',
                'length_cm' => '1',
                'height_cm' => '1',
                'width_cm' => '1',
                'is_active' => '1',
            ],
            [
                'stock_item_id' => '62',
                'stock_unit_id' => '1',
                'deductable' => '100',
                'retail_price' => '30',
                'special_price' => null,
                'weight_gram' => '1',
                'length_cm' => '1',
                'height_cm' => '1',
                'width_cm' => '1',
                'is_active' => '1',
            ],
            [
                'stock_item_id' => '63',
                'stock_unit_id' => '1',
                'deductable' => '1',
                'retail_price' => '48.75',
                'special_price' => null,
                'weight_gram' => '1',
                'length_cm' => '1',
                'height_cm' => '1',
                'width_cm' => '1',
                'is_active' => '1',
            ],
            [
                'stock_item_id' => '64',
                'stock_unit_id' => '1',
                'deductable' => '1',
                'retail_price' => '37.5',
                'special_price' => null,
                'weight_gram' => '1',
                'length_cm' => '1',
                'height_cm' => '1',
                'width_cm' => '1',
                'is_active' => '1',
            ],
            [
                'stock_item_id' => '67',
                'stock_unit_id' => '1',
                'deductable' => '1',
                'retail_price' => '375',
                'special_price' => null,
                'weight_gram' => '1',
                'length_cm' => '1',
                'height_cm' => '1',
                'width_cm' => '1',
                'is_active' => '1',
            ],
            [
                'stock_item_id' => '70',
                'stock_unit_id' => '1',
                'deductable' => '1',
                'retail_price' => '30',
                'special_price' => null,
                'weight_gram' => '80',
                'length_cm' => '7',
                'height_cm' => '2',
                'width_cm' => '2',
                'is_active' => '1',
            ],
            [
                'stock_item_id' => '72',
                'stock_unit_id' => '1',
                'deductable' => '1',
                'retail_price' => '75',
                'special_price' => null,
                'weight_gram' => '1',
                'length_cm' => '1',
                'height_cm' => '1',
                'width_cm' => '1',
                'is_active' => '1',
            ],
            [
                'stock_item_id' => '73',
                'stock_unit_id' => '1',
                'deductable' => '1',
                'retail_price' => '30',
                'special_price' => null,
                'weight_gram' => '1',
                'length_cm' => '1',
                'height_cm' => '1',
                'width_cm' => '1',
                'is_active' => '1',
            ],
            [
                'stock_item_id' => '74',
                'stock_unit_id' => '1',
                'deductable' => '1',
                'retail_price' => '15',
                'special_price' => null,
                'weight_gram' => '1',
                'length_cm' => '1',
                'height_cm' => '1',
                'width_cm' => '1',
                'is_active' => '1',
            ],
            [
                'stock_item_id' => '75',
                'stock_unit_id' => '1',
                'deductable' => '1',
                'retail_price' => '112.5',
                'special_price' => null,
                'weight_gram' => '100',
                'length_cm' => '5',
                'height_cm' => '5',
                'width_cm' => '1',
                'is_active' => '1',
            ],
            [
                'stock_item_id' => '82',
                'stock_unit_id' => '1',
                'deductable' => '1',
                'retail_price' => '37.5',
                'special_price' => null,
                'weight_gram' => '1',
                'length_cm' => '1',
                'height_cm' => '1',
                'width_cm' => '1',
                'is_active' => '1',
            ],
            [
                'stock_item_id' => '96',
                'stock_unit_id' => '1',
                'deductable' => '1',
                'retail_price' => '93.75',
                'special_price' => null,
                'weight_gram' => '1',
                'length_cm' => '1',
                'height_cm' => '1',
                'width_cm' => '1',
                'is_active' => '1',
            ],
            [
                'stock_item_id' => '103',
                'stock_unit_id' => '1',
                'deductable' => '1',
                'retail_price' => '98',
                'special_price' => null,
                'weight_gram' => '1',
                'length_cm' => '1',
                'height_cm' => '1',
                'width_cm' => '1',
                'is_active' => '1',
            ],
            [
                'stock_item_id' => '106',
                'stock_unit_id' => '1',
                'deductable' => '1',
                'retail_price' => '48.75',
                'special_price' => null,
                'weight_gram' => '1',
                'length_cm' => '1',
                'height_cm' => '1',
                'width_cm' => '1',
                'is_active' => '1',
            ],
            [
                'stock_item_id' => '107',
                'stock_unit_id' => '1',
                'deductable' => '1',
                'retail_price' => '30',
                'special_price' => null,
                'weight_gram' => '80',
                'length_cm' => '7',
                'height_cm' => '2',
                'width_cm' => '2',
                'is_active' => '1',
            ],
            [
                'stock_item_id' => '108',
                'stock_unit_id' => '1',
                'deductable' => '1',
                'retail_price' => '30',
                'special_price' => null,
                'weight_gram' => '80',
                'length_cm' => '7',
                'height_cm' => '2',
                'width_cm' => '2',
                'is_active' => '1',
            ],
            [
                'stock_item_id' => '109',
                'stock_unit_id' => '1',
                'deductable' => '1',
                'retail_price' => '30',
                'special_price' => null,
                'weight_gram' => '80',
                'length_cm' => '7',
                'height_cm' => '2',
                'width_cm' => '2',
                'is_active' => '1',
            ],
            [
                'stock_item_id' => '110',
                'stock_unit_id' => '1',
                'deductable' => '1',
                'retail_price' => '30',
                'special_price' => null,
                'weight_gram' => '80',
                'length_cm' => '7',
                'height_cm' => '2',
                'width_cm' => '2',
                'is_active' => '1',
            ],
            [
                'stock_item_id' => '111',
                'stock_unit_id' => '1',
                'deductable' => '1',
                'retail_price' => '30',
                'special_price' => null,
                'weight_gram' => '80',
                'length_cm' => '7',
                'height_cm' => '2',
                'width_cm' => '2',
                'is_active' => '1',
            ],
            [
                'stock_item_id' => '146',
                'stock_unit_id' => '1',
                'deductable' => '1',
                'retail_price' => '2',
                'special_price' => null,
                'weight_gram' => '1',
                'length_cm' => '1',
                'height_cm' => '1',
                'width_cm' => '1',
                'is_active' => '1',
            ],
            [
                'stock_item_id' => '147',
                'stock_unit_id' => '1',
                'deductable' => '50',
                'retail_price' => '74.25',
                'special_price' => null,
                'weight_gram' => '1',
                'length_cm' => '1',
                'height_cm' => '1',
                'width_cm' => '1',
                'is_active' => '1',
            ],
            [
                'stock_item_id' => '148',
                'stock_unit_id' => '1',
                'deductable' => '1',
                'retail_price' => '2',
                'special_price' => null,
                'weight_gram' => '1',
                'length_cm' => '1',
                'height_cm' => '1',
                'width_cm' => '1',
                'is_active' => '1',
            ],
            [
                'stock_item_id' => '149',
                'stock_unit_id' => '1',
                'deductable' => '1',
                'retail_price' => '2',
                'special_price' => null,
                'weight_gram' => '1',
                'length_cm' => '1',
                'height_cm' => '1',
                'width_cm' => '1',
                'is_active' => '1',
            ],
            [
                'stock_item_id' => '150',
                'stock_unit_id' => '1',
                'deductable' => '1',
                'retail_price' => '2',
                'special_price' => null,
                'weight_gram' => '1',
                'length_cm' => '1',
                'height_cm' => '1',
                'width_cm' => '1',
                'is_active' => '1',
            ],
            [
                'stock_item_id' => '151',
                'stock_unit_id' => '1',
                'deductable' => '1',
                'retail_price' => '2',
                'special_price' => null,
                'weight_gram' => '1',
                'length_cm' => '1',
                'height_cm' => '1',
                'width_cm' => '1',
                'is_active' => '1',
            ],
            [
                'stock_item_id' => '152',
                'stock_unit_id' => '1',
                'deductable' => '1',
                'retail_price' => '2',
                'special_price' => null,
                'weight_gram' => '1',
                'length_cm' => '1',
                'height_cm' => '1',
                'width_cm' => '1',
                'is_active' => '1',
            ],
            [
                'stock_item_id' => '153',
                'stock_unit_id' => '1',
                'deductable' => '50',
                'retail_price' => '55',
                'special_price' => null,
                'weight_gram' => '1',
                'length_cm' => '1',
                'height_cm' => '1',
                'width_cm' => '1',
                'is_active' => '1',
            ],
            [
                'stock_item_id' => '154',
                'stock_unit_id' => '1',
                'deductable' => '50',
                'retail_price' => '74.25',
                'special_price' => null,
                'weight_gram' => '1',
                'length_cm' => '1',
                'height_cm' => '1',
                'width_cm' => '1',
                'is_active' => '1',
            ],
            [
                'stock_item_id' => '170',
                'stock_unit_id' => '1',
                'deductable' => '1',
                'retail_price' => '30',
                'special_price' => null,
                'weight_gram' => '1',
                'length_cm' => '1',
                'height_cm' => '1',
                'width_cm' => '1',
                'is_active' => '1',
            ],
            [
                'stock_item_id' => '195',
                'stock_unit_id' => '1',
                'deductable' => '1',
                'retail_price' => '650',
                'special_price' => null,
                'weight_gram' => '1',
                'length_cm' => '1',
                'height_cm' => '1',
                'width_cm' => '1',
                'is_active' => '1',
            ],
            [
                'stock_item_id' => '196',
                'stock_unit_id' => '1',
                'deductable' => '1',
                'retail_price' => '650',
                'special_price' => null,
                'weight_gram' => '1',
                'length_cm' => '1',
                'height_cm' => '1',
                'width_cm' => '1',
                'is_active' => '1',
            ],
            [
                'stock_item_id' => '200',
                'stock_unit_id' => '1',
                'deductable' => '1',
                'retail_price' => '187.5',
                'special_price' => null,
                'weight_gram' => '1',
                'length_cm' => '1',
                'height_cm' => '1',
                'width_cm' => '1',
                'is_active' => '1',
            ],
            [
                'stock_item_id' => '201',
                'stock_unit_id' => '1',
                'deductable' => '1',
                'retail_price' => '187.5',
                'special_price' => null,
                'weight_gram' => '1',
                'length_cm' => '1',
                'height_cm' => '1',
                'width_cm' => '1',
                'is_active' => '1',
            ],
            [
                'stock_item_id' => '246',
                'stock_unit_id' => '1',
                'deductable' => '1',
                'retail_price' => '71.25',
                'special_price' => null,
                'weight_gram' => '80',
                'length_cm' => '23',
                'height_cm' => '2',
                'width_cm' => '5',
                'is_active' => '1',
            ],
            [
                'stock_item_id' => '322',
                'stock_unit_id' => '1',
                'deductable' => '1',
                'retail_price' => '30',
                'special_price' => null,
                'weight_gram' => '80',
                'length_cm' => '7',
                'height_cm' => '2',
                'width_cm' => '2',
                'is_active' => '1',
            ],
            [
                'stock_item_id' => '324',
                'stock_unit_id' => '1',
                'deductable' => '1',
                'retail_price' => '30',
                'special_price' => null,
                'weight_gram' => '80',
                'length_cm' => '7',
                'height_cm' => '2',
                'width_cm' => '2',
                'is_active' => '1',
            ],
            [
                'stock_item_id' => '326',
                'stock_unit_id' => '1',
                'deductable' => '1',
                'retail_price' => '2',
                'special_price' => null,
                'weight_gram' => '1',
                'length_cm' => '1',
                'height_cm' => '1',
                'width_cm' => '1',
                'is_active' => '1',
            ],
            [
                'stock_item_id' => '329',
                'stock_unit_id' => '1',
                'deductable' => '1',
                'retail_price' => '475',
                'special_price' => null,
                'weight_gram' => '1',
                'length_cm' => '1',
                'height_cm' => '1',
                'width_cm' => '1',
                'is_active' => '1',
            ],
            [
                'stock_item_id' => '333',
                'stock_unit_id' => '1',
                'deductable' => '20',
                'retail_price' => '200',
                'special_price' => null,
                'weight_gram' => '1',
                'length_cm' => '1',
                'height_cm' => '1',
                'width_cm' => '1',
                'is_active' => '1',
            ],
            [
                'stock_item_id' => '334',
                'stock_unit_id' => '1',
                'deductable' => '20',
                'retail_price' => '210',
                'special_price' => null,
                'weight_gram' => '1',
                'length_cm' => '1',
                'height_cm' => '1',
                'width_cm' => '1',
                'is_active' => '1',
            ],
            [
                'stock_item_id' => '335',
                'stock_unit_id' => '1',
                'deductable' => '20',
                'retail_price' => '210',
                'special_price' => null,
                'weight_gram' => '1',
                'length_cm' => '1',
                'height_cm' => '1',
                'width_cm' => '1',
                'is_active' => '1',
            ],
            [
                'stock_item_id' => '336',
                'stock_unit_id' => '1',
                'deductable' => '20',
                'retail_price' => '210',
                'special_price' => null,
                'weight_gram' => '1',
                'length_cm' => '1',
                'height_cm' => '1',
                'width_cm' => '1',
                'is_active' => '1',
            ],
            [
                'stock_item_id' => '337',
                'stock_unit_id' => '14',
                'deductable' => '20',
                'retail_price' => '262.5',
                'special_price' => null,
                'weight_gram' => '1',
                'length_cm' => '1',
                'height_cm' => '1',
                'width_cm' => '1',
                'is_active' => '1',
            ],
            [
                'stock_item_id' => '384',
                'stock_unit_id' => '14',
                'deductable' => '20',
                'retail_price' => '262.5',
                'special_price' => null,
                'weight_gram' => '1',
                'length_cm' => '1',
                'height_cm' => '1',
                'width_cm' => '1',
                'is_active' => '1',
            ],
            [
                'stock_item_id' => '390',
                'stock_unit_id' => '1',
                'deductable' => '1',
                'retail_price' => '40',
                'special_price' => null,
                'weight_gram' => '1',
                'length_cm' => '1',
                'height_cm' => '1',
                'width_cm' => '1',
                'is_active' => '1',
            ],
            [
                'stock_item_id' => '397',
                'stock_unit_id' => '1',
                'deductable' => '30',
                'retail_price' => '210',
                'special_price' => null,
                'weight_gram' => '1',
                'length_cm' => '1',
                'height_cm' => '1',
                'width_cm' => '1',
                'is_active' => '1',
            ],
            [
                'stock_item_id' => '398',
                'stock_unit_id' => '1',
                'deductable' => '30',
                'retail_price' => '210',
                'special_price' => null,
                'weight_gram' => '1',
                'length_cm' => '1',
                'height_cm' => '1',
                'width_cm' => '1',
                'is_active' => '1',
            ],
            [
                'stock_item_id' => '399',
                'stock_unit_id' => '1',
                'deductable' => '30',
                'retail_price' => '210',
                'special_price' => null,
                'weight_gram' => '1',
                'length_cm' => '1',
                'height_cm' => '1',
                'width_cm' => '1',
                'is_active' => '1',
            ],
            [
                'stock_item_id' => '401',
                'stock_unit_id' => '1',
                'deductable' => '20',
                'retail_price' => '210',
                'special_price' => null,
                'weight_gram' => '1',
                'length_cm' => '1',
                'height_cm' => '1',
                'width_cm' => '1',
                'is_active' => '1',
            ],
            [
                'stock_item_id' => '402',
                'stock_unit_id' => '1',
                'deductable' => '20',
                'retail_price' => '210',
                'special_price' => null,
                'weight_gram' => '1',
                'length_cm' => '1',
                'height_cm' => '1',
                'width_cm' => '1',
                'is_active' => '1',
            ],
            [
                'stock_item_id' => '440',
                'stock_unit_id' => '1',
                'deductable' => '1',
                'retail_price' => '91.12',
                'special_price' => null,
                'weight_gram' => '1',
                'length_cm' => '1',
                'height_cm' => '1',
                'width_cm' => '1',
                'is_active' => '1',
            ],
            [
                'stock_item_id' => '471',
                'stock_unit_id' => '1',
                'deductable' => '20',
                'retail_price' => '210',
                'special_price' => null,
                'weight_gram' => '1',
                'length_cm' => '1',
                'height_cm' => '1',
                'width_cm' => '1',
                'is_active' => '1',
            ],
            [
                'stock_item_id' => '472',
                'stock_unit_id' => '1',
                'deductable' => '50',
                'retail_price' => '74.25',
                'special_price' => null,
                'weight_gram' => '1',
                'length_cm' => '1',
                'height_cm' => '1',
                'width_cm' => '1',
                'is_active' => '1',
            ],
            [
                'stock_item_id' => '538',
                'stock_unit_id' => '1',
                'deductable' => '1',
                'retail_price' => '99',
                'special_price' => null,
                'weight_gram' => '1',
                'length_cm' => '1',
                'height_cm' => '1',
                'width_cm' => '1',
                'is_active' => '1',
            ],
            [
                'stock_item_id' => '544',
                'stock_unit_id' => '1',
                'deductable' => '1',
                'retail_price' => '30',
                'special_price' => null,
                'weight_gram' => '80',
                'length_cm' => '7',
                'height_cm' => '2',
                'width_cm' => '2',
                'is_active' => '1',
            ],
            [
                'stock_item_id' => '576',
                'stock_unit_id' => '4',
                'deductable' => '50',
                'retail_price' => '76',
                'special_price' => null,
                'weight_gram' => '200',
                'length_cm' => '18',
                'height_cm' => '2',
                'width_cm' => '7',
                'is_active' => '1',
            ],
            [
                'stock_item_id' => '577',
                'stock_unit_id' => '4',
                'deductable' => '50',
                'retail_price' => '123.5',
                'special_price' => null,
                'weight_gram' => '200',
                'length_cm' => '18',
                'height_cm' => '2',
                'width_cm' => '7',
                'is_active' => '1',
            ],
            [
                'stock_item_id' => '578',
                'stock_unit_id' => '4',
                'deductable' => '50',
                'retail_price' => '123.5',
                'special_price' => null,
                'weight_gram' => '200',
                'length_cm' => '18',
                'height_cm' => '2',
                'width_cm' => '7',
                'is_active' => '1',
            ],
            [
                'stock_item_id' => '579',
                'stock_unit_id' => '4',
                'deductable' => '50',
                'retail_price' => '171',
                'special_price' => null,
                'weight_gram' => '200',
                'length_cm' => '18',
                'height_cm' => '2',
                'width_cm' => '7',
                'is_active' => '1',
            ],
            [
                'stock_item_id' => '610',
                'stock_unit_id' => '1',
                'deductable' => '1',
                'retail_price' => '1462.5',
                'special_price' => null,
                'weight_gram' => '1',
                'length_cm' => '1',
                'height_cm' => '1',
                'width_cm' => '1',
                'is_active' => '1',
            ],
            [
                'stock_item_id' => '655',
                'stock_unit_id' => '1',
                'deductable' => '20',
                'retail_price' => '210',
                'special_price' => null,
                'weight_gram' => '1',
                'length_cm' => '1',
                'height_cm' => '1',
                'width_cm' => '1',
                'is_active' => '1',
            ],
            [
                'stock_item_id' => '656',
                'stock_unit_id' => '1',
                'deductable' => '20',
                'retail_price' => '210',
                'special_price' => null,
                'weight_gram' => '1',
                'length_cm' => '1',
                'height_cm' => '1',
                'width_cm' => '1',
                'is_active' => '1',
            ],
            [
                'stock_item_id' => '657',
                'stock_unit_id' => '1',
                'deductable' => '1',
                'retail_price' => '30',
                'special_price' => null,
                'weight_gram' => '1',
                'length_cm' => '1',
                'height_cm' => '1',
                'width_cm' => '1',
                'is_active' => '1',
            ],
            [
                'stock_item_id' => '660',
                'stock_unit_id' => '1',
                'deductable' => '1',
                'retail_price' => '30',
                'special_price' => null,
                'weight_gram' => '1',
                'length_cm' => '1',
                'height_cm' => '1',
                'width_cm' => '1',
                'is_active' => '1',
            ],
            [
                'stock_item_id' => '661',
                'stock_unit_id' => '1',
                'deductable' => '1',
                'retail_price' => '30',
                'special_price' => null,
                'weight_gram' => '1',
                'length_cm' => '1',
                'height_cm' => '1',
                'width_cm' => '1',
                'is_active' => '1',
            ],
            [
                'stock_item_id' => '662',
                'stock_unit_id' => '1',
                'deductable' => '1',
                'retail_price' => '30',
                'special_price' => null,
                'weight_gram' => '1',
                'length_cm' => '1',
                'height_cm' => '1',
                'width_cm' => '1',
                'is_active' => '1',
            ],
            [
                'stock_item_id' => '671',
                'stock_unit_id' => '1',
                'deductable' => '1',
                'retail_price' => '156.25',
                'special_price' => null,
                'weight_gram' => '1',
                'length_cm' => '1',
                'height_cm' => '1',
                'width_cm' => '1',
                'is_active' => '1',
            ],
            [
                'stock_item_id' => '681',
                'stock_unit_id' => '1',
                'deductable' => '1',
                'retail_price' => '1875',
                'special_price' => null,
                'weight_gram' => '1',
                'length_cm' => '1',
                'height_cm' => '1',
                'width_cm' => '1',
                'is_active' => '1',
            ],
            [
                'stock_item_id' => '682',
                'stock_unit_id' => '1',
                'deductable' => '20',
                'retail_price' => '243',
                'special_price' => null,
                'weight_gram' => '1',
                'length_cm' => '1',
                'height_cm' => '1',
                'width_cm' => '1',
                'is_active' => '1',
            ],
            [
                'stock_item_id' => '683',
                'stock_unit_id' => '1',
                'deductable' => '20',
                'retail_price' => '243',
                'special_price' => null,
                'weight_gram' => '1',
                'length_cm' => '1',
                'height_cm' => '1',
                'width_cm' => '1',
                'is_active' => '1',
            ],
            [
                'stock_item_id' => '684',
                'stock_unit_id' => '1',
                'deductable' => '20',
                'retail_price' => '243',
                'special_price' => null,
                'weight_gram' => '1',
                'length_cm' => '1',
                'height_cm' => '1',
                'width_cm' => '1',
                'is_active' => '1',
            ],
            [
                'stock_item_id' => '685',
                'stock_unit_id' => '1',
                'deductable' => '20',
                'retail_price' => '243',
                'special_price' => null,
                'weight_gram' => '1',
                'length_cm' => '1',
                'height_cm' => '1',
                'width_cm' => '1',
                'is_active' => '1',
            ],
            [
                'stock_item_id' => '686',
                'stock_unit_id' => '1',
                'deductable' => '20',
                'retail_price' => '243',
                'special_price' => null,
                'weight_gram' => '1',
                'length_cm' => '1',
                'height_cm' => '1',
                'width_cm' => '1',
                'is_active' => '1',
            ],
            [
                'stock_item_id' => '689',
                'stock_unit_id' => '1',
                'deductable' => '20',
                'retail_price' => '182.25',
                'special_price' => null,
                'weight_gram' => '1',
                'length_cm' => '1',
                'height_cm' => '1',
                'width_cm' => '1',
                'is_active' => '1',
            ],
            [
                'stock_item_id' => '690',
                'stock_unit_id' => '1',
                'deductable' => '20',
                'retail_price' => '182.25',
                'special_price' => null,
                'weight_gram' => '1',
                'length_cm' => '1',
                'height_cm' => '1',
                'width_cm' => '1',
                'is_active' => '1',
            ],
            [
                'stock_item_id' => '691',
                'stock_unit_id' => '14',
                'deductable' => '20',
                'retail_price' => '243',
                'special_price' => null,
                'weight_gram' => '150',
                'length_cm' => '10',
                'height_cm' => '2',
                'width_cm' => '2',
                'is_active' => '1',
            ],
            [
                'stock_item_id' => '692',
                'stock_unit_id' => '1',
                'deductable' => '1',
                'retail_price' => '37.5',
                'special_price' => null,
                'weight_gram' => '1',
                'length_cm' => '1',
                'height_cm' => '1',
                'width_cm' => '1',
                'is_active' => '1',
            ],
            [
                'stock_item_id' => '693',
                'stock_unit_id' => '1',
                'deductable' => '1',
                'retail_price' => '71.25',
                'special_price' => null,
                'weight_gram' => '1',
                'length_cm' => '1',
                'height_cm' => '1',
                'width_cm' => '1',
                'is_active' => '1',
            ],
            [
                'stock_item_id' => '694',
                'stock_unit_id' => '1',
                'deductable' => '1',
                'retail_price' => '51.3',
                'special_price' => null,
                'weight_gram' => '1',
                'length_cm' => '1',
                'height_cm' => '1',
                'width_cm' => '1',
                'is_active' => '1',
            ],
            [
                'stock_item_id' => '701',
                'stock_unit_id' => '1',
                'deductable' => '20',
                'retail_price' => '182.25',
                'special_price' => null,
                'weight_gram' => '1',
                'length_cm' => '1',
                'height_cm' => '1',
                'width_cm' => '1',
                'is_active' => '1',
            ],
            [
                'stock_item_id' => '702',
                'stock_unit_id' => '1',
                'deductable' => '20',
                'retail_price' => '182.25',
                'special_price' => null,
                'weight_gram' => '1',
                'length_cm' => '1',
                'height_cm' => '1',
                'width_cm' => '1',
                'is_active' => '1',
            ],
            [
                'stock_item_id' => '703',
                'stock_unit_id' => '1',
                'deductable' => '20',
                'retail_price' => '182.25',
                'special_price' => null,
                'weight_gram' => '1',
                'length_cm' => '1',
                'height_cm' => '1',
                'width_cm' => '1',
                'is_active' => '1',
            ],
            [
                'stock_item_id' => '704',
                'stock_unit_id' => '1',
                'deductable' => '20',
                'retail_price' => '182.25',
                'special_price' => null,
                'weight_gram' => '1',
                'length_cm' => '1',
                'height_cm' => '1',
                'width_cm' => '1',
                'is_active' => '1',
            ],
            [
                'stock_item_id' => '725',
                'stock_unit_id' => '1',
                'deductable' => '1',
                'retail_price' => '81',
                'special_price' => null,
                'weight_gram' => '1',
                'length_cm' => '1',
                'height_cm' => '1',
                'width_cm' => '1',
                'is_active' => '1',
            ],
            [
                'stock_item_id' => '727',
                'stock_unit_id' => '1',
                'deductable' => '1',
                'retail_price' => '475',
                'special_price' => null,
                'weight_gram' => '1',
                'length_cm' => '1',
                'height_cm' => '1',
                'width_cm' => '1',
                'is_active' => '1',
            ],
            [
                'stock_item_id' => '753',
                'stock_unit_id' => '1',
                'deductable' => '1',
                'retail_price' => '30',
                'special_price' => null,
                'weight_gram' => '80',
                'length_cm' => '7',
                'height_cm' => '2',
                'width_cm' => '2',
                'is_active' => '1',
            ],
            [
                'stock_item_id' => '754',
                'stock_unit_id' => '4',
                'deductable' => '1',
                'retail_price' => '30',
                'special_price' => null,
                'weight_gram' => '80',
                'length_cm' => '7',
                'height_cm' => '2',
                'width_cm' => '2',
                'is_active' => '1',
            ],
            [
                'stock_item_id' => '755',
                'stock_unit_id' => '1',
                'deductable' => '1',
                'retail_price' => '30',
                'special_price' => null,
                'weight_gram' => '80',
                'length_cm' => '7',
                'height_cm' => '2',
                'width_cm' => '2',
                'is_active' => '1',
            ],
            [
                'stock_item_id' => '759',
                'stock_unit_id' => '1',
                'deductable' => '1',
                'retail_price' => '60',
                'special_price' => null,
                'weight_gram' => '1',
                'length_cm' => '1',
                'height_cm' => '1',
                'width_cm' => '1',
                'is_active' => '1',
            ],
            [
                'stock_item_id' => '764',
                'stock_unit_id' => '1',
                'deductable' => '1',
                'retail_price' => '2',
                'special_price' => null,
                'weight_gram' => '1',
                'length_cm' => '1',
                'height_cm' => '1',
                'width_cm' => '1',
                'is_active' => '1',
            ],
            [
                'stock_item_id' => '767',
                'stock_unit_id' => '1',
                'deductable' => '1',
                'retail_price' => '30',
                'special_price' => null,
                'weight_gram' => '1',
                'length_cm' => '1',
                'height_cm' => '1',
                'width_cm' => '1',
                'is_active' => '1',
            ],
            [
                'stock_item_id' => '768',
                'stock_unit_id' => '1',
                'deductable' => '1',
                'retail_price' => '30',
                'special_price' => null,
                'weight_gram' => '1',
                'length_cm' => '1',
                'height_cm' => '1',
                'width_cm' => '1',
                'is_active' => '1',
            ],
            [
                'stock_item_id' => '691',
                'stock_unit_id' => '1',
                'deductable' => '1',
                'retail_price' => '20',
                'special_price' => null,
                'weight_gram' => '1',
                'length_cm' => '1',
                'height_cm' => '1',
                'width_cm' => '1',
                'is_active' => '1',
            ],
            [
                'stock_item_id' => '146',
                'stock_unit_id' => '1',
                'deductable' => '50',
                'retail_price' => '55',
                'special_price' => null,
                'weight_gram' => '1',
                'length_cm' => '1',
                'height_cm' => '1',
                'width_cm' => '1',
                'is_active' => '1',
            ],
            [
                'stock_item_id' => '149',
                'stock_unit_id' => '1',
                'deductable' => '50',
                'retail_price' => '55',
                'special_price' => null,
                'weight_gram' => '1',
                'length_cm' => '1',
                'height_cm' => '1',
                'width_cm' => '1',
                'is_active' => '1',
            ],
            [
                'stock_item_id' => '150',
                'stock_unit_id' => '1',
                'deductable' => '50',
                'retail_price' => '55',
                'special_price' => null,
                'weight_gram' => '1',
                'length_cm' => '1',
                'height_cm' => '1',
                'width_cm' => '1',
                'is_active' => '1',
            ],
            [
                'stock_item_id' => '148',
                'stock_unit_id' => '1',
                'deductable' => '50',
                'retail_price' => '55',
                'special_price' => null,
                'weight_gram' => '1',
                'length_cm' => '1',
                'height_cm' => '1',
                'width_cm' => '1',
                'is_active' => '1',
            ],
            [
                'stock_item_id' => '147',
                'stock_unit_id' => '1',
                'deductable' => '1',
                'retail_price' => '2',
                'special_price' => null,
                'weight_gram' => '1',
                'length_cm' => '1',
                'height_cm' => '1',
                'width_cm' => '1',
                'is_active' => '1',
            ],
            [
                'stock_item_id' => '154',
                'stock_unit_id' => '1',
                'deductable' => '1',
                'retail_price' => '2',
                'special_price' => null,
                'weight_gram' => '1',
                'length_cm' => '1',
                'height_cm' => '1',
                'width_cm' => '1',
                'is_active' => '1',
            ],
            [
                'stock_item_id' => '472',
                'stock_unit_id' => '1',
                'deductable' => '1',
                'retail_price' => '2',
                'special_price' => null,
                'weight_gram' => '1',
                'length_cm' => '1',
                'height_cm' => '1',
                'width_cm' => '1',
                'is_active' => '1',
            ],
            [
                'stock_item_id' => '326',
                'stock_unit_id' => '1',
                'deductable' => '50',
                'retail_price' => '74.25',
                'special_price' => null,
                'weight_gram' => '1',
                'length_cm' => '1',
                'height_cm' => '1',
                'width_cm' => '1',
                'is_active' => '1',
            ],
            [
                'stock_item_id' => '333',
                'stock_unit_id' => '1',
                'deductable' => '1',
                'retail_price' => '12',
                'special_price' => null,
                'weight_gram' => '1',
                'length_cm' => '1',
                'height_cm' => '1',
                'width_cm' => '1',
                'is_active' => '1',
            ],
            [
                'stock_item_id' => '397',
                'stock_unit_id' => '1',
                'deductable' => '1',
                'retail_price' => '9',
                'special_price' => null,
                'weight_gram' => '1',
                'length_cm' => '1',
                'height_cm' => '1',
                'width_cm' => '1',
                'is_active' => '1',
            ],
            [
                'stock_item_id' => '398',
                'stock_unit_id' => '1',
                'deductable' => '1',
                'retail_price' => '9',
                'special_price' => null,
                'weight_gram' => '1',
                'length_cm' => '1',
                'height_cm' => '1',
                'width_cm' => '1',
                'is_active' => '1',
            ],
            [
                'stock_item_id' => '399',
                'stock_unit_id' => '1',
                'deductable' => '1',
                'retail_price' => '9',
                'special_price' => null,
                'weight_gram' => '1',
                'length_cm' => '1',
                'height_cm' => '1',
                'width_cm' => '1',
                'is_active' => '1',
            ],
            [
                'stock_item_id' => '384',
                'stock_unit_id' => '1',
                'deductable' => '1',
                'retail_price' => '15',
                'special_price' => null,
                'weight_gram' => '1',
                'length_cm' => '1',
                'height_cm' => '1',
                'width_cm' => '1',
                'is_active' => '1',
            ],
            [
                'stock_item_id' => '337',
                'stock_unit_id' => '1',
                'deductable' => '1',
                'retail_price' => '15',
                'special_price' => null,
                'weight_gram' => '1',
                'length_cm' => '1',
                'height_cm' => '1',
                'width_cm' => '1',
                'is_active' => '1',
            ],
            [
                'stock_item_id' => '401',
                'stock_unit_id' => '1',
                'deductable' => '1',
                'retail_price' => '12',
                'special_price' => null,
                'weight_gram' => '1',
                'length_cm' => '1',
                'height_cm' => '1',
                'width_cm' => '1',
                'is_active' => '1',
            ],
            [
                'stock_item_id' => '655',
                'stock_unit_id' => '1',
                'deductable' => '1',
                'retail_price' => '12',
                'special_price' => null,
                'weight_gram' => '1',
                'length_cm' => '1',
                'height_cm' => '1',
                'width_cm' => '1',
                'is_active' => '1',
            ],
            [
                'stock_item_id' => '335',
                'stock_unit_id' => '1',
                'deductable' => '1',
                'retail_price' => '12',
                'special_price' => null,
                'weight_gram' => '1',
                'length_cm' => '1',
                'height_cm' => '1',
                'width_cm' => '1',
                'is_active' => '1',
            ],
            [
                'stock_item_id' => '334',
                'stock_unit_id' => '1',
                'deductable' => '1',
                'retail_price' => '12',
                'special_price' => null,
                'weight_gram' => '1',
                'length_cm' => '1',
                'height_cm' => '1',
                'width_cm' => '1',
                'is_active' => '1',
            ],
            [
                'stock_item_id' => '471',
                'stock_unit_id' => '1',
                'deductable' => '1',
                'retail_price' => '12',
                'special_price' => null,
                'weight_gram' => '1',
                'length_cm' => '1',
                'height_cm' => '1',
                'width_cm' => '1',
                'is_active' => '1',
            ],
            [
                'stock_item_id' => '402',
                'stock_unit_id' => '1',
                'deductable' => '1',
                'retail_price' => '12',
                'special_price' => null,
                'weight_gram' => '1',
                'length_cm' => '1',
                'height_cm' => '1',
                'width_cm' => '1',
                'is_active' => '1',
            ],
            [
                'stock_item_id' => '656',
                'stock_unit_id' => '1',
                'deductable' => '1',
                'retail_price' => '12',
                'special_price' => null,
                'weight_gram' => '1',
                'length_cm' => '1',
                'height_cm' => '1',
                'width_cm' => '1',
                'is_active' => '1',
            ],
            [
                'stock_item_id' => '336',
                'stock_unit_id' => '1',
                'deductable' => '1',
                'retail_price' => '12',
                'special_price' => null,
                'weight_gram' => '1',
                'length_cm' => '1',
                'height_cm' => '1',
                'width_cm' => '1',
                'is_active' => '1',
            ],
            [
                'stock_item_id' => '153',
                'stock_unit_id' => '1',
                'deductable' => '1',
                'retail_price' => '2',
                'special_price' => null,
                'weight_gram' => '1',
                'length_cm' => '1',
                'height_cm' => '1',
                'width_cm' => '1',
                'is_active' => '1',
            ],
            [
                'stock_item_id' => '774',
                'stock_unit_id' => '1',
                'deductable' => '1',
                'retail_price' => '156.25',
                'special_price' => null,
                'weight_gram' => '1',
                'length_cm' => '1',
                'height_cm' => '1',
                'width_cm' => '1',
                'is_active' => '1',
            ],
            [
                'stock_item_id' => '152',
                'stock_unit_id' => '1',
                'deductable' => '50',
                'retail_price' => '55',
                'special_price' => null,
                'weight_gram' => '1',
                'length_cm' => '1',
                'height_cm' => '1',
                'width_cm' => '1',
                'is_active' => '1',
            ],
            [
                'stock_item_id' => '683',
                'stock_unit_id' => '1',
                'deductable' => '1',
                'retail_price' => '20',
                'special_price' => null,
                'weight_gram' => '1',
                'length_cm' => '1',
                'height_cm' => '1',
                'width_cm' => '1',
                'is_active' => '1',
            ],
            [
                'stock_item_id' => '682',
                'stock_unit_id' => '1',
                'deductable' => '1',
                'retail_price' => '20',
                'special_price' => null,
                'weight_gram' => '1',
                'length_cm' => '1',
                'height_cm' => '1',
                'width_cm' => '1',
                'is_active' => '1',
            ],
            [
                'stock_item_id' => '701',
                'stock_unit_id' => '1',
                'deductable' => '1',
                'retail_price' => '20',
                'special_price' => null,
                'weight_gram' => '1',
                'length_cm' => '1',
                'height_cm' => '1',
                'width_cm' => '1',
                'is_active' => '1',
            ],
            [
                'stock_item_id' => '684',
                'stock_unit_id' => '1',
                'deductable' => '1',
                'retail_price' => '20',
                'special_price' => null,
                'weight_gram' => '1',
                'length_cm' => '1',
                'height_cm' => '1',
                'width_cm' => '1',
                'is_active' => '1',
            ],
            [
                'stock_item_id' => '685',
                'stock_unit_id' => '1',
                'deductable' => '1',
                'retail_price' => '20',
                'special_price' => null,
                'weight_gram' => '1',
                'length_cm' => '1',
                'height_cm' => '1',
                'width_cm' => '1',
                'is_active' => '1',
            ],
            [
                'stock_item_id' => '686',
                'stock_unit_id' => '1',
                'deductable' => '1',
                'retail_price' => '20',
                'special_price' => null,
                'weight_gram' => '1',
                'length_cm' => '1',
                'height_cm' => '1',
                'width_cm' => '1',
                'is_active' => '1',
            ],
            [
                'stock_item_id' => '702',
                'stock_unit_id' => '1',
                'deductable' => '1',
                'retail_price' => '20',
                'special_price' => null,
                'weight_gram' => '1',
                'length_cm' => '1',
                'height_cm' => '1',
                'width_cm' => '1',
                'is_active' => '1',
            ],
            [
                'stock_item_id' => '689',
                'stock_unit_id' => '1',
                'deductable' => '1',
                'retail_price' => '20',
                'special_price' => null,
                'weight_gram' => '1',
                'length_cm' => '1',
                'height_cm' => '1',
                'width_cm' => '1',
                'is_active' => '1',
            ],
            [
                'stock_item_id' => '703',
                'stock_unit_id' => '1',
                'deductable' => '1',
                'retail_price' => '20',
                'special_price' => null,
                'weight_gram' => '1',
                'length_cm' => '1',
                'height_cm' => '1',
                'width_cm' => '1',
                'is_active' => '1',
            ],
            [
                'stock_item_id' => '690',
                'stock_unit_id' => '1',
                'deductable' => '1',
                'retail_price' => '20',
                'special_price' => null,
                'weight_gram' => '1',
                'length_cm' => '1',
                'height_cm' => '1',
                'width_cm' => '1',
                'is_active' => '1',
            ],
            [
                'stock_item_id' => '704',
                'stock_unit_id' => '1',
                'deductable' => '1',
                'retail_price' => '20',
                'special_price' => null,
                'weight_gram' => '1',
                'length_cm' => '1',
                'height_cm' => '1',
                'width_cm' => '1',
                'is_active' => '1',
            ],
            [
                'stock_item_id' => '62',
                'stock_unit_id' => '8',
                'deductable' => '1000',
                'retail_price' => '225',
                'special_price' => null,
                'weight_gram' => '300',
                'length_cm' => '50',
                'height_cm' => '20',
                'width_cm' => '20',
                'is_active' => '1',
            ],
            [
                'stock_item_id' => '61',
                'stock_unit_id' => '1',
                'deductable' => '1000',
                'retail_price' => '170',
                'special_price' => null,
                'weight_gram' => '1',
                'length_cm' => '1',
                'height_cm' => '1',
                'width_cm' => '1',
                'is_active' => '1',
            ],
            [
                'stock_item_id' => '60',
                'stock_unit_id' => '1',
                'deductable' => '1000',
                'retail_price' => '120',
                'special_price' => null,
                'weight_gram' => '1',
                'length_cm' => '1',
                'height_cm' => '1',
                'width_cm' => '1',
                'is_active' => '1',
            ],
            [
                'stock_item_id' => '151',
                'stock_unit_id' => '1',
                'deductable' => '50',
                'retail_price' => '55',
                'special_price' => null,
                'weight_gram' => '1',
                'length_cm' => '1',
                'height_cm' => '1',
                'width_cm' => '1',
                'is_active' => '1',
            ],
            [
                'stock_item_id' => '49',
                'stock_unit_id' => '1',
                'deductable' => '100',
                'retail_price' => '850',
                'special_price' => null,
                'weight_gram' => '1',
                'length_cm' => '1',
                'height_cm' => '1',
                'width_cm' => '1',
                'is_active' => '1',
            ],
            [
                'stock_item_id' => '776',
                'stock_unit_id' => '1',
                'deductable' => '1',
                'retail_price' => '2599',
                'special_price' => null,
                'weight_gram' => '1',
                'length_cm' => '1',
                'height_cm' => '1',
                'width_cm' => '1',
                'is_active' => '1',
            ],
            [
                'stock_item_id' => '777',
                'stock_unit_id' => '1',
                'deductable' => '1',
                'retail_price' => '2902.5',
                'special_price' => null,
                'weight_gram' => '1',
                'length_cm' => '1',
                'height_cm' => '1',
                'width_cm' => '1',
                'is_active' => '1',
            ],
            [
                'stock_item_id' => '1',
                'stock_unit_id' => '5',
                'deductable' => '343',
                'retail_price' => '324',
                'special_price' => null,
                'weight_gram' => '1',
                'length_cm' => '1',
                'height_cm' => '1',
                'width_cm' => '1',
                'is_active' => '1',
            ],
            
        ];
        StockOption::insert($options);
    }
}
