<?php

namespace Database\Seeders;

use App\Models\StockCategory;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class StockCategorySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $cats = [
            [
                'company_id' => 1,
                'id' => '1',
                'name' => 'Medical',
                'slug' => 'medical',
                'parent_id' => '0',
                'is_active' => '1',
            ],
            [
                'company_id' => 1,
                'id' => '2',
                'name' => 'Consumables',
                'slug' => 'consumables',
                'parent_id' => '0',
                'is_active' => '1',
            ],
            [
                'company_id' => 1,
                'id' => '3',
                'name' => 'Grips and Tips',
                'slug' => 'grips-and-tips',
                'parent_id' => '0',
                'is_active' => '1',
            ],
            [
                'company_id' => 1,
                'id' => '4',
                'name' => 'Inks',
                'slug' => 'inks',
                'parent_id' => '0',
                'is_active' => '1',
            ],
            [
                'company_id' => 1,
                'id' => '5',
                'name' => 'Needles',
                'slug' => 'needles',
                'parent_id' => '0',
                'is_active' => '1',
            ],
            [
                'company_id' => 1,
                'id' => '7',
                'name' => 'Power Supply',
                'slug' => 'power-supply',
                'parent_id' => '0',
                'is_active' => '1',
            ],
            [
                'company_id' => 1,
                'id' => '9',
                'name' => 'Machines',
                'slug' => 'machines',
                'parent_id' => '0',
                'is_active' => '1',
            ],
            [
                'company_id' => 1,
                'id' => '10',
                'name' => 'Shop',
                'slug' => 'shop',
                'parent_id' => '0',
                'is_active' => '1',
            ],
            [
                'company_id' => 1,
                'id' => '12',
                'name' => 'Aluminum Grips',
                'slug' => 'grips-and-tips-aluminum-grips',
                'parent_id' => '3',
                'is_active' => '1',
            ],
            [
                'company_id' => 1,
                'id' => '14',
                'name' => 'Flat Shader',
                'slug' => 'flat-shader',
                'parent_id' => '5',
                'is_active' => '1',
            ],
            [
                'company_id' => 1,
                'id' => '15',
                'name' => 'Ordinary Machines',
                'slug' => 'ordinary-machines',
                'parent_id' => '9',
                'is_active' => '1',
            ],
            [
                'company_id' => 1,
                'id' => '18',
                'name' => 'Stainless Steel Grips',
                'slug' => 'stainless-steel-grips',
                'parent_id' => '3',
                'is_active' => '1',
            ],
            [
                'company_id' => 1,
                'id' => '19',
                'name' => 'Disposable Tips',
                'slug' => 'disposable-tips',
                'parent_id' => '3',
                'is_active' => '1',
            ],
            [
                'company_id' => 1,
                'id' => '20',
                'name' => 'Stainless Steel Tips',
                'slug' => 'stainless-steel-tips',
                'parent_id' => '3',
                'is_active' => '1',
            ],
            [
                'company_id' => 1,
                'id' => '21',
                'name' => 'Tip Sets',
                'slug' => 'tip-sets',
                'parent_id' => '3',
                'is_active' => '1',
            ],
            [
                'company_id' => 1,
                'id' => '23',
                'name' => 'Kuro Sumi',
                'slug' => 'kuro-sumi',
                'parent_id' => '4',
                'is_active' => '1',
            ],
            [
                'company_id' => 1,
                'id' => '25',
                'name' => 'Magnum',
                'slug' => 'magnums',
                'parent_id' => '5',
                'is_active' => '1',
            ],
            [
                'company_id' => 1,
                'id' => '26',
                'name' => 'Round Liner',
                'slug' => 'round-liner',
                'parent_id' => '5',
                'is_active' => '1',
            ],
            [
                'company_id' => 1,
                'id' => '27',
                'name' => 'Round Shader',
                'slug' => 'round-shader',
                'parent_id' => '5',
                'is_active' => '1',
            ],
            [
                'company_id' => 1,
                'id' => '28',
                'name' => 'Rotary',
                'slug' => 'rotary',
                'parent_id' => '9',
                'is_active' => '1',
            ],
            [
                'company_id' => 1,
                'id' => '29',
                'name' => 'Professional Machines',
                'slug' => 'professional-machines',
                'parent_id' => '9',
                'is_active' => '1',
            ],
            [
                'company_id' => 1,
                'id' => '37',
                'name' => 'Disposable Tubes',
                'slug' => 'disposable-tubes',
                'parent_id' => '3',
                'is_active' => '1',
            ],
            [
                'company_id' => 1,
                'id' => '42',
                'name' => 'Furniture',
                'slug' => 'furniture',
                'parent_id' => '10',
                'is_active' => '1',
            ],
            [
                'company_id' => 1,
                'id' => '43',
                'name' => 'Analogue',
                'slug' => 'analogue',
                'parent_id' => '7',
                'is_active' => '1',
            ],
            [
                'company_id' => 1,
                'id' => '44',
                'name' => 'Dual',
                'slug' => 'dual',
                'parent_id' => '7',
                'is_active' => '1',
            ],
            [
                'company_id' => 1,
                'id' => '45',
                'name' => 'Digital',
                'slug' => 'digital',
                'parent_id' => '7',
                'is_active' => '1',
            ],
            [
                'company_id' => 1,
                'id' => '47',
                'name' => 'Machine Spares',
                'slug' => 'machine-spares',
                'parent_id' => '9',
                'is_active' => '1',
            ],
            [
                'company_id' => 1,
                'id' => '48',
                'name' => 'Aftercare and Numbing',
                'slug' => 'aftercare-and-numbing',
                'parent_id' => '1',
                'is_active' => '1',
            ],
            [
                'company_id' => 1,
                'id' => '49',
                'name' => 'Round Magnum',
                'slug' => 'round-magnum',
                'parent_id' => '5',
                'is_active' => '1',
            ],
            [
                'company_id' => 1,
                'id' => '54',
                'name' => 'World Famous',
                'slug' => 'world-famous',
                'parent_id' => '4',
                'is_active' => '1',
            ],
            [
                'company_id' => 1,
                'id' => '56',
                'name' => 'Sterilization',
                'slug' => 'sterilization',
                'parent_id' => '1',
                'is_active' => '1',
            ],
            [
                'company_id' => 1,
                'id' => '61',
                'name' => 'Cartridge Grip',
                'slug' => 'cartridge-grip',
                'parent_id' => '3',
                'is_active' => '1',
            ],
            [
                'company_id' => 1,
                'id' => '62',
                'name' => 'Cosmetic',
                'slug' => 'cosmetic',
                'parent_id' => '0',
                'is_active' => '1',
            ],
            
            
        ];
        StockCategory::insert($cats);
    }
}
